[colors.primary]
background = "#0E1113"
foreground = "#afb1db"

[colors.cursor]
cursor = "#c0caf5"
text = "#1a1b26"

[colors.normal]
black = "#353c52"
red = "#e7034a"
green = "#61b33e"
yellow = "#ffb964"
blue = "#5884d4"
magenta = "#7a44e3"
cyan = "#7df0f0"
white = "#afb1db"

[colors.bright]
black = "#353c52"
red = "#e71c5b"
green = "#6fb352"
yellow = "#ffb964"
blue = "#5f90ea"
magenta = "#8656e3"
cyan = "#97f0f0"
white = "#afb1db"
